FROM python:3.11-slim

WORKDIR /app

# Копіюємо файл залежностей і встановлюємо їх
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо код API
COPY api/ /app/

# Запускаємо uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
